USE [master]
GO

/****** Object:  Database [Dev_Project]    Script Date: 01/03/2023 15:28:50 ******/
CREATE DATABASE [Dev_Project]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dev_Project', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Dev_Project.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Dev_Project_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Dev_Project_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Dev_Project].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Dev_Project] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Dev_Project] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Dev_Project] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Dev_Project] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Dev_Project] SET ARITHABORT OFF 
GO

ALTER DATABASE [Dev_Project] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Dev_Project] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Dev_Project] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Dev_Project] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Dev_Project] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Dev_Project] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Dev_Project] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Dev_Project] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Dev_Project] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Dev_Project] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Dev_Project] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Dev_Project] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Dev_Project] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Dev_Project] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Dev_Project] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Dev_Project] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Dev_Project] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Dev_Project] SET RECOVERY FULL 
GO

ALTER DATABASE [Dev_Project] SET  MULTI_USER 
GO

ALTER DATABASE [Dev_Project] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Dev_Project] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Dev_Project] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Dev_Project] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Dev_Project] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Dev_Project] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Dev_Project] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Dev_Project] SET  READ_WRITE 
GO



USE [Dev_Project]
GO
/****** Object:  Table [dbo].[Projeto]    Script Date: 01/03/2023 15:37:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Projeto](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [nchar](100) NULL,
	[descricao] [nchar](200) NULL,
	[linguagem] [nchar](15) NULL,
	[dt_atualizacao] [smalldatetime] NULL,
	[dono_repositorio] [nchar](100) NULL,
 CONSTRAINT [PK_Projeto_favorito] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Projeto_favorito]    Script Date: 01/03/2023 15:37:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Projeto_favorito](
	[id] [int] NOT NULL
) ON [PRIMARY]
GO
